import type { Metadata } from "next";
import { Anton, Inter, Orbitron, Poppins } from "next/font/google";
import "./globals.css";
import WelcomeScreen from "@/components/WelcomeScreen";
import { useEffect } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const anton = Anton({
  subsets: ["latin"],
  weight: ["400"],
});
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Crafting Your Digital Identity | Kamil Raza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <WelcomeScreen /> */}
        <div className="w-full overflow-x-hidden min-h-screen flex justify-center items-start bg-my-primary">
          <div className="max-w-[1440px]">{children}</div>{" "}
        </div>
      </body>
    </html>
  );
}
