import type { Metadata } from "next";
import { Anton, Poppins } from "next/font/google";
import "./globals.css";
import WelcomeScreen from "@/components/WelcomeScreen";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});
const anton = Anton({
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Crafting Your Digital Identity | Kamil Raza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* <WelcomeScreen /> */}
        {children}
      </body>
    </html>
  );
}
